---
title: "Dan Yavorsky's Resume"
output:
    pagedown::html_resume:
        self_contained: true
knit: pagedown::chrome_print
suppress-bibliography: true
---

<!-- following code chunk hides the side bar after page 1 -->

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> dyavorsky@gmail.com
- <i class="fa fa-home"></i> [www.danyavorsky.com](https://www.danyavorsky.com)
- <i class="fa fa-github"></i> [github.com/dyavorsky](https://github.com/dyavorsky)
- <i class="fa fa-phone"></i> +1 951 201 0927



Skills {#skills}
--------------------------------------------------------------------------------

Statistics, Econometrics, Pedagogy  
R, SQL, Tableau,  
Quarto, Markdown, Latex

Aspiring user of Python, Julia, Vim


Interests {#interests}
--------------------------------------------------------------------------------

Quantitative Marketing, Customer Analytics, Market Research, Causal Inference, Bayesian Methods, Structural Models of Demand, Consumer Search


Personal {#personal}
--------------------------------------------------------------------------------

US Citizen; Married; Two children

Play soccer, cycle, sip bourbon, build mechanical keyboards, collect pocket knives, patinate boots, memorize children books


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<!-- This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown). -->

Last updated on `r Sys.Date()`



Main
================================================================================

Dan Yavorsky {#title}
--------------------------------------------------------------------------------

### Analytics at GBK | Lecturer at UCLA & UCSD

I lead the Marketing Science and Analytics function alongside co-founder and professor Eric Bradlow at GBK Collective where my team and I apply econometric, statistical, and machine learning methods to derive consumer insights and inform marketing strategy for our clients. 

I also teach courses in Analytics, Econometrics, and related topics at the UCSD Rady and UCLA Anderson business schools. 


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### PhD Quantitative Marketing

UCLA Anderson

Los Angeles, CA

2020

### MBA, Management

UCLA Anderson

Los Angeles, CA

2014

### CFA Charterholder

Chartered Financial Analyst (CFA) Institute

San Francisco, CA

2012

### BA, Economics & Mathematics

Claremont McKenna College

Claremont, CA

2006


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Senior Vice President, Analytics

GBK Collective

Los Angeles, CA

Present - 2022

- Lead the day-to-day operations of our Marketing Science and Analytics function. I interface with client and project teams, execute analyses, extend and research analytic methodology, explore analytic solutions to business problems, develop best practices implementing those solutions, and grow and manage our analytics team.

### Manager, Advanced Analytics

Bain & Co.

Los Angeles, CA

2021 - 2020

- Performed marketing analytics to support strategic management consulting engagements, including conjoint analysis, maximum-difference scaling, customer segmentation, perceptual mapping, factor analysis, and other statistical or econometric analysis.
- Developed ecosystem of statistical and machine learning models to enable media conglomerate to value content on its streaming platforms and optimize media licensing decisions.

### Graduate Student Research Assistant

University of California, Los Angeles

Los Angeles, CA

2019 - 2015

- Provided research assistance for Chen, Chevalier, Rossi, and Oehlsen “The Value of Flexible Work: Evidence from Uber Drivers” _Journal of Political Economy_, 2019.
- Provided research assistance for Honka, Seiler, and Ursu "The Sequential Search Model: A Framework for Empirical Research" _Quantitative Marketing and Economics_, 2024.
- Updated and maintained Professor Rossi’s R package `bayesm` by editing functions that draw from posterior distributions of Bayesian statistical models, authoring vignettes, and revising documentation.

### Analyst, Senior Analyst, Research Associate

Cornerstone Research

San Francisco, CA

2014 - 2006

- Performed economic, financial, and statistical analyses to support professors engaged as expert witnesses in over 100 commercial litigation matters related to consumer fraud, bankruptcy, forensic accounting, asset pricing, and other matters.
- Led substantial internal initiatives including firm-wide analyst training and West Coast analyst recruiting.


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Lecturer, UCLA

University of California, Los Angeles

Los Angeles, CA

Present - 2021

- Econometrics (MFE 402)
- Marketing Strategy and Policy (EMBA 411)


### Lecturer, UCSD

University of California, San Diego

San Diego, CA

Present - 2021

- Customer Analytics (MGT 100 for BA)
- Business Analytics (MGT 153 for BA)
- Marketing Analytics (MGTA 495 for MsBA)


### Teaching Assistant

University of California, Los Angeles

Los Angeles, CA

2020 - 2015

- Econometrics (with Peter Rossi for MFE)
- R Programming (with Peter Rossi for MsBA)
- Data Science (with Stephan Seiler for MsBA)
- Customer Analytics (with Anand Bodapati for MsBA)
- Pricing (with Elisabeth Honka for MBA)
- Statistics (with Elisa Long for MBA)
- Customer Analytics (with Brett Hollenbeck for MBA)


Publications {data-icon=file}
--------------------------------------------------------------------------------

### Consumer search in the U.S. auto industry: The role of dealership visits [[PDF](https://link.springer.com/content/pdf/10.1007/s11129-020-09229-4.pdf)]

_Quantitative Marketing and Economics_ 

Los Angeles, CA

2020

Dan Yavorsky, Elisabeth Honka, and Keith Chen

<!--
In Progress {data-icon=file-edit}
--------------------------------------------------------------------------------

### Outside Good Uncertainty: Ordinal Dual Response in Choice-Based Conjoint Analysis [[link](https://dyavorsky.github.io/likert_dualresponse/)]

_with Prachi Bhalerao and Geoffery Zheng_

Los Angeles, CA

2024


### Discrete Choice Model Estimation with R [[link](http://dcme-r.danyavorsky.com/)]

_a book providing instruction on how to estimate discrete choice models "by hand" in R_

Los Angeles, CA

2024
-->



